### ISSUE TITLE
Why on earth does this install so many unnecessary programs?

### ISSUE THREAD

**Issue by xirianlight** [st3v3nhunt/dotfiles#4]
I mean, I love Wireshark as much as the next guy, but Garmin software? Checking for 3rd party browsers? Why on earth is the bloatware content of this installer so high? Any light you can shed on this, or is this entire repo just a malware package?

**Comment by st3v3nhunt** [comment]
Unnecessary to you, sure. Unnecessary to me, not so much.
This is _my_ set of personal dot files. I started with the basics after having used https://dotfiles.github.io/ for inspiration. That might  be a good starting point if you want to automate your environment setup.
